trigger:
#  - main  # or your default branch
  - pytest_allure_report  # or your default branch


pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'  # or any version you need

  - script: |
      python -m pip install --upgrade pip
      pip install -r playwright/tests/requirements.txt
      pip install pytest
    displayName: 'Install dependencies'

  - script: |
      playwright install
    displayName: 'Install playwright'

  - script: |
      sudo apt-get update
      sudo apt-get install -y xvfb
      xvfb-run pytest playwright/tests/  # path to your test folder
    displayName: 'Run tests with pytest'
