[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
addopts = -v --maxfail=5 --disable-warnings -q --alluredir=allure-results --clean-alluredir --log-cli-level=INFO
markers =
    smoke: mark test as smoke test
    regression: mark test as regression test