name: Cypress Tests All

on:
  push:
    branches: [taf_cypress]
  pull_request:
  workflow_run:
    workflows: ["Cypress Tests Five"]
    types:
      - completed

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TAF_test/JS/cypress/cypress_demo02_schulte_tables/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: check current directory content
        run: ls

      - name: Run Cypress tests
        run: npx cypress run