openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://script.crazyegg.com/pages/data-scripts/0040/0639/site/editor.swagger.io.json?t=1
    description: Optional server description, e.g. Main (production) server
get:
responses:
    '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string